branch-defaults:
  default:
    environment: Production-env
    group_suffix: null
  dev:
    environment: Production-env
environment-defaults:
  Production-env:
    branch: dev
    repository: origin
global:
  application_name: portfolio
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
